### ISSUE TITLE
[feat]: Option to turn on allow-self-payment

### ISSUE THREAD

**Issue by adamj7** [Start9Labs/lnd-startos#107]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

I am trying to use lnbits with LND, but in order for me to fund my lightning wallet using the funds already on my node, LNBits documents say that I must enable 2 options
------------
https://github.com/lnbits/lnbits/blob/main/docs/guide/faq.md
Funding my LNbits wallet from my node it doesn't work.

If you want to send sats from the same node that is the funding source of your LNbits, you will need to edit the lnd.conf file. The parameters to be included are:

allow-circular-route=1
allow-self-payment=1
------------

I can find an option to enable the circular route, but I cannot find an option to allow-self-payment. When I SSH and modify the lnd.conf manually, it wipes it and replaces it when I restart the service.

### Describe the Use Case

Trying to load sats from my own lightning node running LND, to a wallet on LNBits on the same node.

### Describe Preferred Solution

Enable a toggle like allow circular route but for allow self payment.

**Comment by Dominion5254** [comment]
Self payment is not required to fund a wallet with your underlying lightning node.

You can fund any wallet by opening the Superuser Account (found in LNbits Properties) then navigating to "Manage Server" > "Topup". On the resulting form, the "Wallet ID" will can be found in LNbits Properties as the last query param of your desired wallet url, and it will be preceded by "wal=".

**Comment by adamj7** [comment]
Self-payment I believe is a requirement for continual funding on a LNBits wallet (think hosting a wallet for family members, and using it to pay them for chores - they create an invoice, I pay it with funds from my own node - except it has to LEAVE my node first to just come back to it - which causes fees).
An option within the GUI to enable this as an option is what I'm asking for, not that the code is written to actually do this. It shouldn't be difficult to enable this.

**Comment by Dominion5254** [comment]
While that is one way LNbits could be used, routing payments as a rebalance creates unnecessary fees when the funds don't actually need to leave the underlying node. LNbits is like an accounting layer on top of the chosen LN implementation. It doesn't make much sense to route a LN tx through other nodes just to send those sats back to the same node when LNbits can simply edit the accounting layer database and decrease/increase the appropriate wallet balances.

Continual funding of a LNbits wallet can work in several different ways without the need for `allow-self-payments=true`:
1. A LNbits wallet can receive funds from any other LN node (provided the underlying node has sufficient inbound liquidity).
2. Additional funds can be allocated to an LNbits wallet using the Superuser user (the method I detailed in my previous comment).
3. One LNbits account can pay another LNbits account without `allow-self-payments=true` even though they are on the same node as long as it is another LNbits account paying the invoice.

If you are using multiple LNbits wallets for family members, any of the above methods should allow paying a family member and increasing their LNbits wallet balance without the need for `allow-self-payments=true` or paying the associated fees. That said, it is not apparent to me why self-payment would be a requirement for continual funding of a LNbits wallet.
