### ISSUE TITLE
[bug]: LNCLI connection error to LND instance with default installation.

### ISSUE THREAD

**Issue by Reckless-Satoshi** [Start9Labs/lnd-startos#108]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

StartOS v0.3.4.4

### Browser

Firefox

### Browser Version

Not relevant

### Current Behavior
Any LNCLI command leads to a general gRPC connection error (same error one would get if the ip:port to the LND instance was wrong). 
```error
[lncli] rpc error: code = Unavailable desc = connection error: desc = “transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused”
```
This issue seem to also have been reported here: https://community.start9.com/t/lncli-wallet-bumpfee/362/2

**Some initial debugging:**
- The ip:port (localhost:10009) is right.
- LND is installed, properly configured running and synced. 
- LNCLI is installed and accessible.
- The TLS certificate is correct, path is correct.
- The path to LND dir is correct. 

So I am out of ideas why LNCLI cannot talk to LND.

### Expected Behavior

LNCLI should be wired with LND gRPC by default.

### Steps to Reproduce

I replicated this issue in two different machines running StartOS.

1. Install LND from the market place, config it and let it sync. 
2. Then, for example, run this LNCLI command from `instructions.md` to become a watchtower:
https://github.com/Start9Labs/lnd-wrapper/blob/7c6e52206fdee7080cc1537ad55cd3d5fd731ce3/docs/instructions.md?plain=1#L64
The command will fail with a connection error to the LND instance. 

### Anything else?

Being able to use `LNCLI` is critical as there will never be a way to use the full functionality of LND from web UIs. At the moment, it is not possible to recover LND from seedphrase (`lncli create`) for example (worth opening another issue).

**Comment by Dominion5254** [comment]
I wasn't able to reproduce the error with the steps provided. Running the command `sudo docker exec -ti lnd.embassy lncli --rpcserver=lnd.embassy tower info` returned the expected tower information (assuming the tower server is enabled in config).

However I was able to reproduce the indicated error when 1) --rpcserver was not specified (it defaults to localhost:10009) and 2) --rpcserver was specified as localhost:10009. This is expected as the correct rpcserver needs to be specified. Can you confirm the error is still presenting when the --rpcserver is set to `lnd.embassy`?

In the example of recovering LND from seedphrase, the recommended and supported flow is using the [system backup](https://docs.start9.com/latest/support/faq/faq-lightning#how-do-i-find-my-lnd-seed-so-i-can-write-it-down-to-backup).

**Comment by Dominion5254** [comment]
Closing as completed as the solution is to specify the rpcserver as indicated above.
