### ISSUE TITLE
LND Properties tab not appearing

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/lnd-startos#29]
This is normally a result of LND having not started up yet, but one user has it as a recurring issue.  Re-installs do not help.  Logs report "Error: missing field 'cipher_seed_mnemonic' at line 1 column 135" and "waiting for wallet encryption password," and asks for lncli commands to create or unlock a wallet.

**Comment by ProofOfKeags** [comment]
I can also spin up a 0.2.x box no problem to try and reproduce this.

**Comment by kn0wmad** [comment]
Sounds good, thanks for looking into this

**Comment by elvece** [comment]
@kn0wmad Does this issue reflect a problem in the EOS v0.2.x version of LND?

**Comment by kn0wmad** [comment]
> @kn0wmad Does this issue reflect a problem in the EOS v0.2.x version of LND?

Yes.  I filed a report for a similar issue on 0.3 however, which was my own, not of a user

**Comment by ProofOfKeags** [comment]
If we can't reproduce we should probably close this as a ghost.
