### ISSUE TITLE
[bug]: LND often resorts to "syncing" status

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/lnd-startos#79]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.19

### Browser

Firefox

### Browser Version

102

### Current Behavior

LND often seems to fall out of sync with the chain.  Reason is unknown and this could also be an upstream issue

### Expected Behavior

Remain synced when there are no interruptions to network or connection

### Steps to Reproduce

1. Just happens randomly

**Comment by Dominion5254** [comment]
I haven't been able to reproduce this behavior on the Server One (NUC) or Server Pure.

I suspect this related to limitations of the Raspberry Pi. Closing until this can be reliably reproduced on more performant hardware.
