### ISSUE TITLE
[feat]: LND backup options

### ISSUE THREAD

**Issue by tuvok137** [Start9Labs/lnd-startos#91]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

-allow users to use RTL or Thunderhub made channel backups to work with LND service on eOS
-allow users to write down 24 word seed of the LND service when started the first time (first setup)
-allow users to enter a 24 word seed into LND service when started first (recovery)
-allow users to choose between LND backup options: -1 legacy (24 words + channel backup file)
                                                                                      -2 eOS backup system

 

### Describe the Use Case

more abilities for users

### Describe Preferred Solution

let the user decide how he wants to backup the lnd service  

### Describe Alternatives

-

### Anything else?

-

**Comment by Dominion5254** [comment]
RTL and Thunderhub both leverage the same APIs for the SCB that is already backed up by LND. LND will automatically update the channel.backup file any time a channel is opened or closed. This file is then backed up to the specified target (i.e. LAN shared folder or attached drive) any time the user initiates a backup of the LND service.

The recommended flow is to backup LND any time a channel open or close occurs, which will ensure the backup has a complete SCB as well as the wallet.db to allow recovery of both off chain and on chain funds. While the Aezeed Cipherseed has been exposed for fresh installations >= 0.16.4, the recommended backup procedure remains to be the supported backup flow outlined above as this will restore both the on-chain and off chain funds.
